public class ArithmeticException  
{  
void division(int a, int b)  
{  
int res = a / b;  
System.out.println("Division process has been done successfully.");  
System.out.println("Result came after division is: " + res);  
}  
  
// main method  
public static void main(String argvs[])  
{  
// creating an object of the class ArithmeticException  
ArithmeticException a = new ArithmeticException();  
a.division(2, 1);  
}  
}  